"""upgrade the database run 3

Revision ID: 551ac075f4a4
Revises: 58eb9011f407
Create Date: 2019-12-02 16:42:32.819276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551ac075f4a4'
down_revision = '58eb9011f407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_comments_email', table_name='comments')
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_comments_email', 'comments', ['email'], unique=True)
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
